spring:
  application:
    name: currency-converter
  messages:
    encoding: UTF-8
    basename: i18n/messages

jwt:
  header:
    string: Authorization
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles